org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Java/jdk-21
unityStreamingAssets=.json
# Android Resolver Properties Start
android.useAndroidX=true
android.enableJetifier=true
# Android Resolver Properties End
unityTemplateVersion=20
unityProjectPath=D:/SHSD/Projects (Github)/Halabessa/Halabessa-Card-Game/unity/Halabessa
unity.projectPath=D:/SHSD/Projects (Github)/Halabessa/Halabessa-Card-Game/unity/Halabessa
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=23
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.halabessa.game
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=1.0
unity.namespace=com.halabessa.game
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.69f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.69f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.0.69f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never