org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=35,36
# Set this to your local Java 17 or Java 21 path if you encounter the "25.0.1" plugin load error
org.gradle.java.home=C:/Program Files/Java/jdk-21
kotlin.incremental=false
android.nonTransitiveRClass=false
android.experimental.suppressExtractNativeLibsWarnings=true
unityStreamingAssets=.json
unityTemplateVersion=20
unity.projectPath=D:/SHSD/Projects (Github)/Halabessa/Halabessa-Card-Game/unity/Halabessa
unity.debugSymbolLevel=none
unity.buildToolsVersion=35.0.0
unity.minSdkVersion=23
unity.targetSdkVersion=35
unity.compileSdkVersion=35
unity.applicationId=com.halabessa.game
unity.abiFilters=arm64-v8a
unity.namespace=com.halabessa.game
unity.androidNdkVersion=27.0.12077973
