org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
kotlin.incremental=false
android.nonTransitiveRClass=false
android.experimental.suppressExtractNativeLibsWarnings=true
unityStreamingAssets=.json
unityTemplateVersion=20
unity.projectPath=D:/SHSD/Projects (Github)/Halabessa/Halabessa-Card-Game/unity/Halabessa
unity.debugSymbolLevel=none
unity.buildToolsVersion=35.0.0
unity.minSdkVersion=23
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.halabessa.game
unity.abiFilters=arm64-v8a
unity.namespace=com.halabessa.game
unity.androidNdkVersion=27.0.12077973
